CREATE CONSTRAINT cliente_id IF NOT EXISTS FOR (c:Cliente)   REQUIRE c.id IS UNIQUE;
CREATE CONSTRAINT agente_id  IF NOT EXISTS FOR (a:Agente)    REQUIRE a.id IS UNIQUE;
CREATE CONSTRAINT poliza_id  IF NOT EXISTS FOR (p:Poliza)    REQUIRE p.id IS UNIQUE;
CREATE CONSTRAINT siniestro_id IF NOT EXISTS FOR (s:Siniestro) REQUIRE s.id IS UNIQUE;
CREATE CONSTRAINT vehiculo_id IF NOT EXISTS FOR (v:Vehiculo) REQUIRE v.id IS UNIQUE;
